### ISSUE TITLE
This Script is Not Working Anymore

### ISSUE THREAD

**Issue by kalpesh9** [Damzaky/Full-Size-Instagram-Profile-Picture-Getter#1]
Please update and fix the script its not working

**Comment by damzaky** [comment]
can you tell me the details (the username of the profile picture you wish to see)? because in my case, it still works perfectly

**Comment by kalpesh9** [comment]
username=kalpeshnarwani

I've uploaded the file on the hosting as you said but when i openen it as you've said engine.php?u=username but it shows a blank page (i've changed username with my username)

**Comment by damzaky** [comment]
have you checked the log file? there should be an error message or something, because i've tried your username on my engine and it worked perfectly

**Comment by kalpesh9** [comment]
I was thinking that my siteground hosting makes some problem so I created an account on free hosting site but it shows error when I navigate to https://kalpesh999.000webhostapp.com/engine.php?u=kalpeshnarwani

errors:
Notice: Undefined offset: 0 in /storage/ssd4/823/5098823/public_html/engine.php on line 6
Notice: Undefined offset: 1 in /storage/ssd4/823/5098823/public_html/engine.php on line 7

**Comment by damzaky** [comment]
apparently instagram has changed their api :(, I will try to fix this as soon as possible
